name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        bun-version: [1.0.0]
    timeout-minutes: 20
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Install Playwright browsers
        run: bun playwright install --with-deps

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Run unit / component tests
        run: bun run test:unit

      - name: Run Playwright tests
        run: bun run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
